package HelloNaming;


/**
* HelloNaming/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorldName.idl
* Monday, 27 April 2020 13:36:50 o'clock BST
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
